import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// eslint-config-next ships legacy (.eslintrc) shareable configs; FlatCompat
// bridges them into the ESLint 9 flat-config format. This mirrors what
// create-next-app generates for ESLint 9 projects.
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every build; linting it flags a
    // triple-slash reference Next itself writes.
    ignores: [".next/**", "node_modules/**", "playwright-report/**", "test-results/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
